[package]
name = "nodiv"
version = "0.1.0"
authors = ["Amrit Rathie <tirma.eithar@gmail.com>"]
edition = "2018"

[dev-dependencies]
proptest = "0.10.1"
paste = "1.0.0"

[dependencies]
static_assertions = "1.1.0"

